<a href="https://colab.research.google.com/github/SalmaSherif7070/Canada-Airlines-Dashboard/blob/main/A2_%7C_Linear_Regression_%7C_Salma_Sherif_202200622.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Import necessary libraries

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

# Operations

In [ ]:
def append_ones(matrix):
    ones_column = np.ones((matrix.shape[0], 1))
    new_matrix = np.concatenate((ones_column, matrix), axis=1)
    return new_matrix

In [ ]:
def get_inverse(matrix):
    # try:
      inverse = np.linalg.inv(matrix)
      return inverse
    # except np.linalg.LinAlgError:
    #     return None

In [ ]:
def get_transpose(matrix):
    return np.transpose(matrix)

In [ ]:
def matrix_multiply(matrix1, matrix2):
    # try:
      result = np.matmul(matrix1, matrix2)
      return result
    # except ValueError:
    #     return None

# Example usage
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
result_matrix = matrix_multiply(matrix1, matrix2)

# Part 1

**Prepare the datafram**

In [ ]:
df = pd.DataFrame()
for x in range(5):
    y = 6*x + 3
    new_data = {'x': x, 'y': y}
    df = df.append(new_data, ignore_index=True)

In [ ]:
df

x   y
0  0   3
1  1   9
2  2  15
3  3  21
4  4  27

In [ ]:
column_values = df['y'].tolist()
y = np.array(column_values).reshape(-1, 1)
column_values = df['x'].tolist()
x = np.array(column_values).reshape(-1, 1)

In [ ]:
x.shape

(5, 1)

In [ ]:
y.shape

(5, 1)

In [ ]:
def MSSW(x,y):
  # x = append_ones(x)
  x_t = get_transpose(x)
  xx_t=matrix_multiply(x_t, x)
  step = get_inverse(xx_t)
  pesodo = matrix_multiply(step,x_t)
  w = matrix_multiply(pesodo, y)
  return w

In [ ]:
MSSW(x,y)

array([[7.]])

**With noise**

In [ ]:
newdf = pd.DataFrame()
for x in range(5):
    y = 6*x + 7
    new_data = {'x': x, 'y': y+0.4}
    newdf = newdf.append(new_data, ignore_index=True)
newdf

In [ ]:
column_values = newdf['y'].tolist()
y = np.array(column_values).reshape(-1, 1)
column_values = newdf['x'].tolist()
x = np.array(column_values).reshape(-1, 1)

In [ ]:
MSSW(x,y)

array([[8.46666667]])

# Part 2

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Iris.csv')
# df = pd.read_csv('Iris.csv')

df

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [ ]:
class1 = df[df['Species'] == 'Iris-setosa']
class2 = df[df['Species'].isin(['Iris-versicolor', 'Iris-virginica'])]
class1

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0    1            5.1           3.5            1.4           0.2  Iris-setosa
1    2            4.9           3.0            1.4           0.2  Iris-setosa
2    3            4.7           3.2            1.3           0.2  Iris-setosa
3    4            4.6           3.1            1.5           0.2  Iris-setosa
4    5            5.0           3.6            1.4           0.2  Iris-setosa
5    6            5.4           3.9            1.7           0.4  Iris-setosa
6    7            4.6           3.4            1.4           0.3  Iris-setosa
7    8            5.0           3.4            1.5           0.2  Iris-setosa
8    9            4.4           2.9            1.4           0.2  Iris-setosa
9   10            4.9           3.1            1.5           0.1  Iris-setosa
10  11            5.4           3.7            1.5           0.2  Iris-setosa
11  12            4.8           3.4            1.6           0.2  Iris-setosa
12  13            4.8           3.0            1.4           0.1  Iris-setosa
13  14            4.3           3.0            1.1           0.1  Iris-setosa
14  15            5.8           4.0            1.2           0.2  Iris-setosa
15  16            5.7           4.4            1.5           0.4  Iris-setosa
16  17            5.4           3.9            1.3           0.4  Iris-setosa
17  18            5.1           3.5            1.4           0.3  Iris-setosa
18  19            5.7           3.8            1.7           0.3  Iris-setosa
19  20            5.1           3.8            1.5           0.3  Iris-setosa
20  21            5.4           3.4            1.7           0.2  Iris-setosa
21  22            5.1           3.7            1.5           0.4  Iris-setosa
22  23            4.6           3.6            1.0           0.2  Iris-setosa
23  24            5.1           3.3            1.7           0.5  Iris-setosa
24  25            4.8           3.4            1.9           0.2  Iris-setosa
25  26            5.0           3.0            1.6           0.2  Iris-setosa
26  27            5.0           3.4            1.6           0.4  Iris-setosa
27  28            5.2           3.5            1.5           0.2  Iris-setosa
28  29            5.2           3.4            1.4           0.2  Iris-setosa
29  30            4.7           3.2            1.6           0.2  Iris-setosa
30  31            4.8           3.1            1.6           0.2  Iris-setosa
31  32            5.4           3.4            1.5           0.4  Iris-setosa
32  33            5.2           4.1            1.5           0.1  Iris-setosa
33  34            5.5           4.2            1.4           0.2  Iris-setosa
34  35            4.9           3.1            1.5           0.1  Iris-setosa
35  36            5.0           3.2            1.2           0.2  Iris-setosa
36  37            5.5           3.5            1.3           0.2  Iris-setosa
37  38            4.9           3.1            1.5           0.1  Iris-setosa
38  39            4.4           3.0            1.3           0.2  Iris-setosa
39  40            5.1           3.4            1.5           0.2  Iris-setosa
40  41            5.0           3.5            1.3           0.3  Iris-setosa
41  42            4.5           2.3            1.3           0.3  Iris-setosa
42  43            4.4           3.2            1.3           0.2  Iris-setosa
43  44            5.0           3.5            1.6           0.6  Iris-setosa
44  45            5.1           3.8            1.9           0.4  Iris-setosa
45  46            4.8           3.0            1.4           0.3  Iris-setosa
46  47            5.1           3.8            1.6           0.2  Iris-setosa
47  48            4.6           3.2            1.4           0.2  Iris-setosa
48  49            5.3           3.7            1.5           0.2  Iris-setosa
49  50            5.0           3.3            1.4           0.2  Iris-setosa

In [ ]:
trainclass1,testclass1= train_test_split(class1 ,test_size=0.2, random_state=42)
trainclass2,testclass2= train_test_split(class2 ,test_size=0.2, random_state=42)
# testclass1

In [ ]:
xclass1 = trainclass1.drop("Id", axis=1)
xclass2 = trainclass2.drop("Id", axis = 1)
xclass1=xclass1.drop("Species", axis=1)
xclass2=xclass2.drop("Species", axis=1)
xclass2.shape

(80, 4)

In [ ]:
matrixclass1 = xclass1.copy()
matrixclass1.insert(0, 'Ones', 1)

matrixclass2 = xclass2.copy()
matrixclass2.insert(0, 'Ones', 1)
matrixclass2*=-1

In [ ]:
x = pd.concat([matrixclass1, matrixclass2], axis=0, ignore_index=True).values
y = np.ones((120, 1))
x

array([[ 1. ,  4.8,  3. ,  1.4,  0.1],
       [ 1. ,  5. ,  3.6,  1.4,  0.2],
       [ 1. ,  4.9,  3.1,  1.5,  0.1],
       [ 1. ,  4.4,  2.9,  1.4,  0.2],
       [ 1. ,  4.6,  3.1,  1.5,  0.2],
       [ 1. ,  4.6,  3.4,  1.4,  0.3],
       [ 1. ,  4.5,  2.3,  1.3,  0.3],
       [ 1. ,  5.1,  3.8,  1.6,  0.2],
       [ 1. ,  4.6,  3.2,  1.4,  0.2],
       [ 1. ,  5.7,  4.4,  1.5,  0.4],
       [ 1. ,  4.9,  3.1,  1.5,  0.1],
       [ 1. ,  5.4,  3.9,  1.3,  0.4],
       [ 1. ,  4.8,  3.4,  1.9,  0.2],
       [ 1. ,  4.9,  3.1,  1.5,  0.1],
       [ 1. ,  5.4,  3.4,  1.5,  0.4],
       [ 1. ,  5.1,  3.5,  1.4,  0.2],
       [ 1. ,  5.1,  3.8,  1.9,  0.4],
       [ 1. ,  5.2,  3.5,  1.5,  0.2],
       [ 1. ,  5.5,  4.2,  1.4,  0.2],
       [ 1. ,  5.4,  3.9,  1.7,  0.4],
       [ 1. ,  4.7,  3.2,  1.6,  0.2],
       [ 1. ,  4.8,  3.4,  1.6,  0.2],
       [ 1. ,  5.5,  3.5,  1.3,  0.2],
       [ 1. ,  4.9,  3. ,  1.4,  0.2],
       [ 1. ,  5.1,  3.7,  1.5,  0.4],
       [ 1. ,  4.7,  3.2,

In [ ]:
w = MSSW(x,y)
w
# y.shape
# x.shape

array([[-0.71101489],
       [ 0.11937926],
       [ 0.47625549],
       [-0.41428179],
       [-0.18001396]])

In [ ]:
# test class 1
Y_hat = []
for i in range(len(testclass1)):
  pre = testclass1[["SepalLengthCm","SepalWidthCm","PetalLengthCm","PetalWidthCm"]].iloc[i].values
  pre = np.insert(pre, 0, 1)
  Y_hat.append(matrix_multiply(pre,w)[0])
  print(Y_hat[i])

0.7573710523651616
0.8596625468465103
0.6395439400652474
0.6567733534985565
0.9307148796302804
1.0264150477965235
0.7702936488032656
0.615794243361623
1.2229807152012646
1.03216334839415


In [ ]:
# test class 2
for i in range(len(testclass2)):
  pre = testclass2[["SepalLengthCm","SepalWidthCm","PetalLengthCm","PetalWidthCm"]].iloc[i].values
  pre = np.insert(pre, 0, 1)
  Y_hat.append(matrix_multiply(pre,w)[0])
  print(Y_hat[i])

0.7573710523651616
0.8596625468465103
0.6395439400652474
0.6567733534985565
0.9307148796302804
1.0264150477965235
0.7702936488032656
0.615794243361623
1.2229807152012646
1.03216334839415
-1.008268243902081
-1.2217877801884525
-1.138718733825213
-0.5577868995994055
-0.7306028703005228
-0.7549355365295182
-1.0682885331895933
-1.3632384331858303
-0.7916078296712464
-0.5504864477527673


In [ ]:
def acc(Y_hat,Y_test):
  c = 0
  for i in range(len(Y_test)):
    if Y_hat[i] > 0 and Y_test[i] == "Iris-setosa":
      c+=1
    elif Y_hat[i] < 0 and Y_test[i] != "Iris-setosa":
      c+=1
  print(c/len(Y_test) *100 , "%" )

In [ ]:
Y_test = pd.concat([testclass1, testclass2], axis=0, ignore_index=True)["Species"]
acc(Y_hat,Y_test)

100.0 %
